## CI for Java
name: CI for Build Core
on:
  workflow_dispatch:
# push:
#   branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Checkout the debezium repository
        uses: actions/checkout@v4
        with:
          repository: debezium/debezium
          path: core
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Cache the Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Maven build debezium core 
        run: mvn clean install -f core/pom.xml -pl debezium-bom,debezium-core,debezium-embedded,debezium-storage -am -DskipTests -DskipITs -Dformat.formatter.goal=validate -Dformat.imports.goal=check -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
      - name: Maven Package spanner connector core
        run: mvn -B clean install
#       - name: Maven unit tests
#         run:  mvn test --batch-mode -Dmaven.test.failure.ignore=true
# # Tests report
#       - name: Report
#         uses: dorny/test-reporter@v1
#         if: always()
#         with:
#           name: Maven Tests Report
#           path: ./**/target/**/TEST-*.xml
#           reporter: java-junit
#           fail-on-error: true
